name: dockerless_image_downloader
description: Downloads Docker container images without Docker installed.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  path_provider: ^2.1.5
  file_picker: ^8.1.6
  archive: ^3.6.1
  crypto: ^3.0.6
  provider: ^6.1.2
  url_launcher: ^6.3.1
  google_fonts: ^6.1.0
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/box-icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/box-icon.png
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: assets/box-icon.png
    background_color: "#141210"
    theme_color: "#141210"
  windows:
    generate: true
    image_path: assets/box-icon.png
    icon_size: 256
  macos:
    generate: true
    image_path: assets/box-icon.png
